= Quarkus in Action -- Book code

This repository represents the book code developed in the book link:https://www.manning.com/books/quarkus-in-action[Quarkus in Action] currently in the Manning Early Access Program (MEAP) with the expected release in winter 2024.

---

_Available in_: link:README.adoc[English]

> Great thanks to every contributor that made this happen (https://github.com/xstefank/quarkus-in-action/graphs/contributors).

Folders in this repository correspond to the individual chapters in the book. The commit history contains the step by step implementations added per section of the book.

- link:chapter-02/README.adoc[Chapter 2: Your first Quarkus application]
- link:chapter-03/README.adoc[Chapter 3: Enhancing developer productivity with Quarkus]
- link:chapter-04/README.adoc[Chapter 4: Handling communications]
- link:chapter-05/README.adoc[Chapter 5: Testing Quarkus applications]
- link:chapter-06/README.adoc[Chapter 6: Exposing and securing web applications]
- link:chapter-07/README.adoc[Chapter 7:Database access]
- link:chapter-08/README.adoc[Chapter 8: Reactive programming]
- link:chapter-09/README.adoc[Chapter 9: Reactive messaging]
- link:chapter-10/README.adoc[Chapter 10: Cloud-native application patterns]
- link:chapter-11/README.adoc[Chapter 11: Quarkus applications in the cloud]
- link:chapter-12/README.adoc[Chapter 12: Custom Quarkus extensions]

Chapter 12 contains the full Car Rental application that you start building from Chapter 4. Everything can be built from source. Feel free to experiment with this codebase as you find fit.

If you have any comments, ideas, or proposals, feel free to open link:https://github.com/xstefank/quarkus-in-action/issues/new/choose[an issue in this repository] or propose link:https://github.com/xstefank/quarkus-in-action/compare[a pull request].

You can also reach out to authors directly:

Martin Stefanko

- X - link:https://twitter.com/xstefank[@xstefank]
- Mastodon - link:https://mastodon.cloud/@xstefank[@xstefank@mastodon.cloud]
- BlueSky - link:https://bsky.app/profile/xstefank.bsky.social[@xstefank.bsky.social]
- LinkedIn - https://www.linkedin.com/in/martin-stefanko/

Jan Martiska

- X - link:https://twitter.com/janmartiska[@janmartiska]
- LinkedIn - https://www.linkedin.com/in/janmartiska/
